from game_base import GameBase
from PIL import ImageTk


class Images:
    def __init__(self, game):
        self.game = game

    def get_images(self):
        self.game.all_images =  {'no_img': ImageTk.PhotoImage(file='set_cards/no_card.png'),
                            '1bse': ImageTk.PhotoImage(file='set_cards/1bse.png'),
                            '1bsf': ImageTk.PhotoImage(file='set_cards/1bsf.png'),
                            '1bss': ImageTk.PhotoImage(file='set_cards/1bss.png'),
                            '1gse': ImageTk.PhotoImage(file='set_cards/1gse.png'),
                            '1gsf': ImageTk.PhotoImage(file='set_cards/1gsf.png'),
                            '1gss': ImageTk.PhotoImage(file='set_cards/1gss.png'),
                            '1rse': ImageTk.PhotoImage(file='set_cards/1rse.png'),
                            '1rsf': ImageTk.PhotoImage(file='set_cards/1rsf.png'),
                            '1rss': ImageTk.PhotoImage(file='set_cards/1rss.png'),

                            '1bce': ImageTk.PhotoImage(file='set_cards/1bce.png'),
                            '1bcf': ImageTk.PhotoImage(file='set_cards/1bcf.png'),
                            '1bcs': ImageTk.PhotoImage(file='set_cards/1bcs.png'),
                            '1gce': ImageTk.PhotoImage(file='set_cards/1gce.png'),
                            '1gcf': ImageTk.PhotoImage(file='set_cards/1gcf.png'),
                            '1gcs': ImageTk.PhotoImage(file='set_cards/1gcs.png'),
                            '1rce': ImageTk.PhotoImage(file='set_cards/1rce.png'),
                            '1rcf': ImageTk.PhotoImage(file='set_cards/1rcf.png'),
                            '1rcs': ImageTk.PhotoImage(file='set_cards/1rcs.png'),

                            '1bwe': ImageTk.PhotoImage(file='set_cards/1bwe.png'),
                            '1bwf': ImageTk.PhotoImage(file='set_cards/1bwf.png'),
                            '1bws': ImageTk.PhotoImage(file='set_cards/1bws.png'),
                            '1gwe': ImageTk.PhotoImage(file='set_cards/1gwe.png'),
                            '1gwf': ImageTk.PhotoImage(file='set_cards/1gwf.png'),
                            '1gws': ImageTk.PhotoImage(file='set_cards/1gws.png'),
                            '1rwe': ImageTk.PhotoImage(file='set_cards/1rwe.png'),
                            '1rwf': ImageTk.PhotoImage(file='set_cards/1rwf.png'),
                            '1rws': ImageTk.PhotoImage(file='set_cards/1rws.png'),

                            '2bse': ImageTk.PhotoImage(file='set_cards/2bse.png'),
                            '2bsf': ImageTk.PhotoImage(file='set_cards/2bsf.png'),
                            '2bss': ImageTk.PhotoImage(file='set_cards/2bss.png'),
                            '2gse': ImageTk.PhotoImage(file='set_cards/2gse.png'),
                            '2gsf': ImageTk.PhotoImage(file='set_cards/2gsf.png'),
                            '2gss': ImageTk.PhotoImage(file='set_cards/2gss.png'),
                            '2rse': ImageTk.PhotoImage(file='set_cards/2rse.png'),
                            '2rsf': ImageTk.PhotoImage(file='set_cards/2rsf.png'),
                            '2rss': ImageTk.PhotoImage(file='set_cards/2rss.png'),

                            '2bce': ImageTk.PhotoImage(file='set_cards/2bce.png'),
                            '2bcf': ImageTk.PhotoImage(file='set_cards/2bcf.png'),
                            '2bcs': ImageTk.PhotoImage(file='set_cards/2bcs.png'),
                            '2gce': ImageTk.PhotoImage(file='set_cards/2gce.png'),
                            '2gcf': ImageTk.PhotoImage(file='set_cards/2gcf.png'),
                            '2gcs': ImageTk.PhotoImage(file='set_cards/2gcs.png'),
                            '2rce': ImageTk.PhotoImage(file='set_cards/2rce.png'),
                            '2rcf': ImageTk.PhotoImage(file='set_cards/2rcf.png'),
                            '2rcs': ImageTk.PhotoImage(file='set_cards/2rcs.png'),

                            '2bwe': ImageTk.PhotoImage(file='set_cards/2bwe.png'),
                            '2bwf': ImageTk.PhotoImage(file='set_cards/2bwf.png'),
                            '2bws': ImageTk.PhotoImage(file='set_cards/2bws.png'),
                            '2gwe': ImageTk.PhotoImage(file='set_cards/2gwe.png'),
                            '2gwf': ImageTk.PhotoImage(file='set_cards/2gwf.png'),
                            '2gws': ImageTk.PhotoImage(file='set_cards/2gws.png'),
                            '2rwe': ImageTk.PhotoImage(file='set_cards/2rwe.png'),
                            '2rwf': ImageTk.PhotoImage(file='set_cards/2rwf.png'),
                            '2rws': ImageTk.PhotoImage(file='set_cards/2rws.png'),

                            '3bse': ImageTk.PhotoImage(file='set_cards/3bse.png'),
                            '3bsf': ImageTk.PhotoImage(file='set_cards/3bsf.png'),
                            '3bss': ImageTk.PhotoImage(file='set_cards/3bss.png'),
                            '3gse': ImageTk.PhotoImage(file='set_cards/3gse.png'),
                            '3gsf': ImageTk.PhotoImage(file='set_cards/3gsf.png'),
                            '3gss': ImageTk.PhotoImage(file='set_cards/3gss.png'),
                            '3rse': ImageTk.PhotoImage(file='set_cards/3rse.png'),
                            '3rsf': ImageTk.PhotoImage(file='set_cards/3rsf.png'),
                            '3rss': ImageTk.PhotoImage(file='set_cards/3rss.png'),

                            '3bce': ImageTk.PhotoImage(file='set_cards/3bce.png'),
                            '3bcf': ImageTk.PhotoImage(file='set_cards/3bcf.png'),
                            '3bcs': ImageTk.PhotoImage(file='set_cards/3bcs.png'),
                            '3gce': ImageTk.PhotoImage(file='set_cards/3gce.png'),
                            '3gcf': ImageTk.PhotoImage(file='set_cards/3gcf.png'),
                            '3gcs': ImageTk.PhotoImage(file='set_cards/3gcs.png'),
                            '3rce': ImageTk.PhotoImage(file='set_cards/3rce.png'),
                            '3rcf': ImageTk.PhotoImage(file='set_cards/3rcf.png'),
                            '3rcs': ImageTk.PhotoImage(file='set_cards/3rcs.png'),

                            '3bwe': ImageTk.PhotoImage(file='set_cards/3bwe.png'),
                            '3bwf': ImageTk.PhotoImage(file='set_cards/3bwf.png'),
                            '3bws': ImageTk.PhotoImage(file='set_cards/3bws.png'),
                            '3gwe': ImageTk.PhotoImage(file='set_cards/3gwe.png'),
                            '3gwf': ImageTk.PhotoImage(file='set_cards/3gwf.png'),
                            '3gws': ImageTk.PhotoImage(file='set_cards/3gws.png'),
                            '3rwe': ImageTk.PhotoImage(file='set_cards/3rwe.png'),
                            '3rwf': ImageTk.PhotoImage(file='set_cards/3rwf.png'),
                            '3rws': ImageTk.PhotoImage(file='set_cards/3rws.png'),
                            }
